---
title: "hatchR Package Authors and Citation"
author: 
  - name: Bryan Maitland
    affiliation: US Forest Service Rocky Mountain Research Station
    email: bryan.maitland@usda.gov
    orcid: 0000-0002-4491-5064
  - name: Morgan Sparks
    affiliation: US Forest Service Rocky Mountain Research Station
    email: morgan.sparks@usda.gov
    orcid: 0000-0003-0787-2218
  - name: Eli Felts
    affiliation: US Fish & Wildlife Service
    email: eli_felts@fws.gov
    orcid: 0000-0002-5888-9266
format: html
editor: visual
theme: cyborg
---

```{r echo=FALSE, warning=FALSE}

library(shiny)
library(rbibutils)
library(downloadthis)
library(RefManageR)

```

## Citation

```{r echo=FALSE}
bibentry(
  
  bibtype    = "Unpublished",
  title      = "{hatchR}: predicting fish developmental phenology",
  author     = c(person(given  = "Bryan M.",
                        family = "Maitland",
                        email  = "bryan.maitland@usda.gov"),
                 person(given  = "Morgan R.",
                        family = "Sparks"),
                 person(given  = "Eli",
                        family = "Felts",
                        email = "eli_felts@fws.gov")
                        ),
  year       = "2025",
  note       = "In preparation"
  
)


```

## Shiny App Feedback

This application was authored and is maintained by Eli Felts. Send bug reports and feature requests to eli_felts\@fws.gov.
